@startuml parking

Class ParkingBoy << Entity >> {
  ParkingLot[] parkingLots

  + Ticket park(Car car)

  + void setParkingLots (ParkingLot[] parkingLots)
  + ParkingLot[] getParkingLots()
}

class ParkingLot << Entity >> {
  ParkingLotId id
  int capacity
  Map <Ticket, Car> parkedCars

  + Ticket park(Car car)
  + Car take(Ticket ticket)
}

Class Car << Value Object >> {
    PlateNumber plateNumber
}

Class Ticket << Value Object >> {
  TicketID id
  + Boolean validate()
}

Ticket "1" *--> "1" Car
ParkingLot "1" o--> "0..many" Ticket
ParkingBoy "1" o--> "0..many" ParkingLot

@enduml
